graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 95
         y 74
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 96
         y 234
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 349
         y 234
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 335
         y 78
      ]
   ]
   node [
      id 5
      label "A"
      graphics [
         x 218
         y 157
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 2
      label ""
      weight 1.0
   ]
]