graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 127
         y 172
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 117
         y 384
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 348
         y 403
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 371
         y 260
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 247
         y 314
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 511
         y 308
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 505
         y 456
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 315
         y 569
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 117
         y 508
      ]
   ]
   node [
      id 12
      label "N"
      graphics [
         x 477
         y 585
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 10
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 12
      label ""
      weight 1.0
   ]
]