graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 117
         y 122
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 336
         y 287
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 118
         y 482
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 327
         y 489
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 317
         y 661
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 232
         y 690
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 425
         y 698
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 539
         y 528
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 574
         y 652
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 174
         y 586
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 512
         y 100
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 246
         y 810
      ]
   ]
   node [
      id 12
      label "N"
      graphics [
         x 414
         y 833
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 12
      label ""
      weight 1.0
   ]
]